### ISSUE TITLE
Extend JPL to dictionaries

### ISSUE THREAD

**Issue by ssardina** [SWI-Prolog/packages-jpl#54]
Dictionaries fail at `Term.getTerm(Term)`. For example, this query won't be handled as it returns a dictionary and cannot be converted back to Java:

```
?- current_prolog_flag(abi_version, Y).
Y = abi{built_in:2033063160, foreign_interface:2, qlf:67, qlf_min_load:67, record:3, vmi:3726870942}.
```

This means that test ` public void ReportPrologFlags()` in `Test_Report.java` throws an exception:

```
org.jpl7.JPLException: unknown term type=44

	at org.jpl7.Term.getTerm(Term.java:364)
	at org.jpl7.Variable.getSubst(Variable.java:159)
	at org.jpl7.Term.getSubsts(Term.java:802)
	at org.jpl7.Query.getCurrentSolutionBindings(Query.java:514)
	at org.jpl7.Query.nextSolution(Query.java:502)
	
```

**Comment by ssardina** [comment]
A working version is already in 7c23d5153b7072f201b2534efd0fd305d12bee5f

Needs to complete unit testing and documentation before creating PR
